name: 'telegram_medical'
version: '1.0.0'
config-version: 2

profile: 'telegram_medical'  # Must match your profile name

# Folder structure
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

# Target configuration
target-path: "target"
clean-targets: ["target"]
require-dbt-version: ">=1.0.0"

# Project-specific variables
vars:
  default_schema: public